language: objective-c

before_install:
    - gem update cocoapods --no-document
    - pod --version
    - brew update
    - brew install xctool

env:
  matrix:
    - SDK=iphonesimulator7.0
    - SDK=iphonesimulator7.1
    #- SDK=iphonesimulator8.0

script:
    - xctool -workspace NovaCamera.xcworkspace -sdk $SDK -scheme NovaCamera build